import { createLink, type LinkComponent } from '@tanstack/react-router';
import { Button, type ButtonProps } from '@mantine/core';

const MantineButtonComponent = ({ ...props }: ButtonProps) => {
  return <Button {...props} />;
};

const CreatedButtonLink = createLink(MantineButtonComponent);

/**
 * CustomButtonLink is a link component styled as a Mantine Button, using TanStack Router's createLink.
 * This works as type safe anchor/navigation method for the possible routes generated by Tanstack router
 *
 * @param props - Button and link props passed to the component.
 * @returns {JSX.Element} The rendered button link component.
 *
 * @example
 * <CustomButtonLink to="/dashboard">Go to Dashboard</CustomButtonLink>
 */
export const CustomButtonLink: LinkComponent<typeof MantineButtonComponent> = (props) => {
  return <CreatedButtonLink preload="intent" {...props} />;
};
