/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appReferenceDataRouteImport } from './routes/(app)/reference-data'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appCreatePortfolioRouteRouteImport } from './routes/(app)/create-portfolio/route'
import { Route as appAnalyzeRouteRouteImport } from './routes/(app)/analyze/route'
import { Route as appCreatePortfolioMetadataRouteImport } from './routes/(app)/create-portfolio/metadata'
import { Route as appAnalyzeStockProfileRouteImport } from './routes/(app)/analyze/stock-profile'
import { Route as appAnalyzePortfolioIdRouteImport } from './routes/(app)/analyze/$portfolioId'
import { Route as appCreatePortfolioPortfolioIdUniverseRouteImport } from './routes/(app)/create-portfolio/$portfolioId/universe'
import { Route as appCreatePortfolioPortfolioIdSummaryRouteImport } from './routes/(app)/create-portfolio/$portfolioId/summary'
import { Route as appCreatePortfolioPortfolioIdSubmitRouteImport } from './routes/(app)/create-portfolio/$portfolioId/submit'
import { Route as appCreatePortfolioPortfolioIdPreviewRouteImport } from './routes/(app)/create-portfolio/$portfolioId/preview'
import { Route as appCreatePortfolioPortfolioIdMultifundRouteImport } from './routes/(app)/create-portfolio/$portfolioId/multifund'
import { Route as appCreatePortfolioPortfolioIdCorrectionsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/corrections'
import { Route as appCreatePortfolioPortfolioIdCalculationsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/calculations'
import { Route as appCreatePortfolioPortfolioIdBenchmarkRouteImport } from './routes/(app)/create-portfolio/$portfolioId/benchmark'
import { Route as appAnalyzePrortfolioIdIdeaGenerationRouteImport } from './routes/(app)/analyze/$prortfolioId/idea-generation'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'

const appHelpLazyRouteImport = createFileRoute('/(app)/help')()

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appHelpLazyRoute = appHelpLazyRouteImport
  .update({
    id: '/help',
    path: '/help',
    getParentRoute: () => appRouteRoute,
  } as any)
  .lazy(() => import('./routes/(app)/help.lazy').then((d) => d.Route))
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appReferenceDataRoute = appReferenceDataRouteImport.update({
  id: '/reference-data',
  path: '/reference-data',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreatePortfolioRouteRoute = appCreatePortfolioRouteRouteImport.update({
  id: '/create-portfolio',
  path: '/create-portfolio',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyzeRouteRoute = appAnalyzeRouteRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreatePortfolioMetadataRoute =
  appCreatePortfolioMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appAnalyzeStockProfileRoute = appAnalyzeStockProfileRouteImport.update({
  id: '/stock-profile',
  path: '/stock-profile',
  getParentRoute: () => appAnalyzeRouteRoute,
} as any)
const appAnalyzePortfolioIdRoute = appAnalyzePortfolioIdRouteImport.update({
  id: '/$portfolioId',
  path: '/$portfolioId',
  getParentRoute: () => appAnalyzeRouteRoute,
} as any)
const appCreatePortfolioPortfolioIdUniverseRoute =
  appCreatePortfolioPortfolioIdUniverseRouteImport.update({
    id: '/$portfolioId/universe',
    path: '/$portfolioId/universe',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdSummaryRoute =
  appCreatePortfolioPortfolioIdSummaryRouteImport.update({
    id: '/$portfolioId/summary',
    path: '/$portfolioId/summary',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdSubmitRoute =
  appCreatePortfolioPortfolioIdSubmitRouteImport.update({
    id: '/$portfolioId/submit',
    path: '/$portfolioId/submit',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdPreviewRoute =
  appCreatePortfolioPortfolioIdPreviewRouteImport.update({
    id: '/$portfolioId/preview',
    path: '/$portfolioId/preview',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdMultifundRoute =
  appCreatePortfolioPortfolioIdMultifundRouteImport.update({
    id: '/$portfolioId/multifund',
    path: '/$portfolioId/multifund',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCorrectionsRoute =
  appCreatePortfolioPortfolioIdCorrectionsRouteImport.update({
    id: '/$portfolioId/corrections',
    path: '/$portfolioId/corrections',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCalculationsRoute =
  appCreatePortfolioPortfolioIdCalculationsRouteImport.update({
    id: '/$portfolioId/calculations',
    path: '/$portfolioId/calculations',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdBenchmarkRoute =
  appCreatePortfolioPortfolioIdBenchmarkRouteImport.update({
    id: '/$portfolioId/benchmark',
    path: '/$portfolioId/benchmark',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appAnalyzePrortfolioIdIdeaGenerationRoute =
  appAnalyzePrortfolioIdIdeaGenerationRouteImport.update({
    id: '/$prortfolioId/idea-generation',
    path: '/$prortfolioId/idea-generation',
    getParentRoute: () => appAnalyzeRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport.update({
    id: '/$portfolioId/create-benchmark/preview',
    path: '/$portfolioId/create-benchmark/preview',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport.update({
    id: '/$portfolioId/create-benchmark/metadata',
    path: '/$portfolioId/create-benchmark/metadata',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport.update({
    id: '/$portfolioId/create-benchmark/corrections',
    path: '/$portfolioId/create-benchmark/corrections',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authIndexRoute
  '/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/reference-data': typeof appReferenceDataRoute
  '/settings': typeof appSettingsRoute
  '/register': typeof authRegisterRoute
  '/help': typeof appHelpLazyRoute
  '/analyze/$portfolioId': typeof appAnalyzePortfolioIdRoute
  '/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/analyze/$prortfolioId/idea-generation': typeof appAnalyzePrortfolioIdIdeaGenerationRoute
  '/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/create-portfolio/$portfolioId/multifund': typeof appCreatePortfolioPortfolioIdMultifundRoute
  '/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/create-portfolio/$portfolioId/summary': typeof appCreatePortfolioPortfolioIdSummaryRoute
  '/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof authIndexRoute
  '/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/reference-data': typeof appReferenceDataRoute
  '/settings': typeof appSettingsRoute
  '/register': typeof authRegisterRoute
  '/help': typeof appHelpLazyRoute
  '/analyze/$portfolioId': typeof appAnalyzePortfolioIdRoute
  '/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/analyze/$prortfolioId/idea-generation': typeof appAnalyzePrortfolioIdIdeaGenerationRoute
  '/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/create-portfolio/$portfolioId/multifund': typeof appCreatePortfolioPortfolioIdMultifundRoute
  '/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/create-portfolio/$portfolioId/summary': typeof appCreatePortfolioPortfolioIdSummaryRoute
  '/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/(app)/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/reference-data': typeof appReferenceDataRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/help': typeof appHelpLazyRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/analyze/$portfolioId': typeof appAnalyzePortfolioIdRoute
  '/(app)/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/(app)/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/(app)/analyze/$prortfolioId/idea-generation': typeof appAnalyzePrortfolioIdIdeaGenerationRoute
  '/(app)/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/(app)/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/(app)/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/(app)/create-portfolio/$portfolioId/multifund': typeof appCreatePortfolioPortfolioIdMultifundRoute
  '/(app)/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/(app)/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/(app)/create-portfolio/$portfolioId/summary': typeof appCreatePortfolioPortfolioIdSummaryRoute
  '/(app)/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/create-portfolio'
    | '/dashboard'
    | '/reference-data'
    | '/settings'
    | '/register'
    | '/help'
    | '/analyze/$portfolioId'
    | '/analyze/stock-profile'
    | '/create-portfolio/metadata'
    | '/analyze/$prortfolioId/idea-generation'
    | '/create-portfolio/$portfolioId/benchmark'
    | '/create-portfolio/$portfolioId/calculations'
    | '/create-portfolio/$portfolioId/corrections'
    | '/create-portfolio/$portfolioId/multifund'
    | '/create-portfolio/$portfolioId/preview'
    | '/create-portfolio/$portfolioId/submit'
    | '/create-portfolio/$portfolioId/summary'
    | '/create-portfolio/$portfolioId/universe'
    | '/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/create-portfolio/$portfolioId/create-benchmark/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/create-portfolio'
    | '/dashboard'
    | '/reference-data'
    | '/settings'
    | '/register'
    | '/help'
    | '/analyze/$portfolioId'
    | '/analyze/stock-profile'
    | '/create-portfolio/metadata'
    | '/analyze/$prortfolioId/idea-generation'
    | '/create-portfolio/$portfolioId/benchmark'
    | '/create-portfolio/$portfolioId/calculations'
    | '/create-portfolio/$portfolioId/corrections'
    | '/create-portfolio/$portfolioId/multifund'
    | '/create-portfolio/$portfolioId/preview'
    | '/create-portfolio/$portfolioId/submit'
    | '/create-portfolio/$portfolioId/summary'
    | '/create-portfolio/$portfolioId/universe'
    | '/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/create-portfolio/$portfolioId/create-benchmark/preview'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/analyze'
    | '/(app)/create-portfolio'
    | '/(app)/dashboard'
    | '/(app)/reference-data'
    | '/(app)/settings'
    | '/(auth)/register'
    | '/(app)/help'
    | '/(auth)/'
    | '/(app)/analyze/$portfolioId'
    | '/(app)/analyze/stock-profile'
    | '/(app)/create-portfolio/metadata'
    | '/(app)/analyze/$prortfolioId/idea-generation'
    | '/(app)/create-portfolio/$portfolioId/benchmark'
    | '/(app)/create-portfolio/$portfolioId/calculations'
    | '/(app)/create-portfolio/$portfolioId/corrections'
    | '/(app)/create-portfolio/$portfolioId/multifund'
    | '/(app)/create-portfolio/$portfolioId/preview'
    | '/(app)/create-portfolio/$portfolioId/submit'
    | '/(app)/create-portfolio/$portfolioId/summary'
    | '/(app)/create-portfolio/$portfolioId/universe'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRegisterRoute: typeof authRegisterRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/help': {
      id: '/(app)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof appHelpLazyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reference-data': {
      id: '/(app)/reference-data'
      path: '/reference-data'
      fullPath: '/reference-data'
      preLoaderRoute: typeof appReferenceDataRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-portfolio': {
      id: '/(app)/create-portfolio'
      path: '/create-portfolio'
      fullPath: '/create-portfolio'
      preLoaderRoute: typeof appCreatePortfolioRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analyze': {
      id: '/(app)/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof appAnalyzeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-portfolio/metadata': {
      id: '/(app)/create-portfolio/metadata'
      path: '/metadata'
      fullPath: '/create-portfolio/metadata'
      preLoaderRoute: typeof appCreatePortfolioMetadataRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/analyze/stock-profile': {
      id: '/(app)/analyze/stock-profile'
      path: '/stock-profile'
      fullPath: '/analyze/stock-profile'
      preLoaderRoute: typeof appAnalyzeStockProfileRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/analyze/$portfolioId': {
      id: '/(app)/analyze/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/analyze/$portfolioId'
      preLoaderRoute: typeof appAnalyzePortfolioIdRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/universe': {
      id: '/(app)/create-portfolio/$portfolioId/universe'
      path: '/$portfolioId/universe'
      fullPath: '/create-portfolio/$portfolioId/universe'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdUniverseRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/summary': {
      id: '/(app)/create-portfolio/$portfolioId/summary'
      path: '/$portfolioId/summary'
      fullPath: '/create-portfolio/$portfolioId/summary'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdSummaryRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/submit': {
      id: '/(app)/create-portfolio/$portfolioId/submit'
      path: '/$portfolioId/submit'
      fullPath: '/create-portfolio/$portfolioId/submit'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdSubmitRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/preview': {
      id: '/(app)/create-portfolio/$portfolioId/preview'
      path: '/$portfolioId/preview'
      fullPath: '/create-portfolio/$portfolioId/preview'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdPreviewRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/multifund': {
      id: '/(app)/create-portfolio/$portfolioId/multifund'
      path: '/$portfolioId/multifund'
      fullPath: '/create-portfolio/$portfolioId/multifund'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdMultifundRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/corrections': {
      id: '/(app)/create-portfolio/$portfolioId/corrections'
      path: '/$portfolioId/corrections'
      fullPath: '/create-portfolio/$portfolioId/corrections'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCorrectionsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/calculations': {
      id: '/(app)/create-portfolio/$portfolioId/calculations'
      path: '/$portfolioId/calculations'
      fullPath: '/create-portfolio/$portfolioId/calculations'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCalculationsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/benchmark': {
      id: '/(app)/create-portfolio/$portfolioId/benchmark'
      path: '/$portfolioId/benchmark'
      fullPath: '/create-portfolio/$portfolioId/benchmark'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdBenchmarkRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/analyze/$prortfolioId/idea-generation': {
      id: '/(app)/analyze/$prortfolioId/idea-generation'
      path: '/$prortfolioId/idea-generation'
      fullPath: '/analyze/$prortfolioId/idea-generation'
      preLoaderRoute: typeof appAnalyzePrortfolioIdIdeaGenerationRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/preview': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
      path: '/$portfolioId/create-benchmark/preview'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/preview'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
      path: '/$portfolioId/create-benchmark/metadata'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/metadata'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'
      path: '/$portfolioId/create-benchmark/corrections'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/corrections'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
  }
}

interface appAnalyzeRouteRouteChildren {
  appAnalyzePortfolioIdRoute: typeof appAnalyzePortfolioIdRoute
  appAnalyzeStockProfileRoute: typeof appAnalyzeStockProfileRoute
  appAnalyzePrortfolioIdIdeaGenerationRoute: typeof appAnalyzePrortfolioIdIdeaGenerationRoute
}

const appAnalyzeRouteRouteChildren: appAnalyzeRouteRouteChildren = {
  appAnalyzePortfolioIdRoute: appAnalyzePortfolioIdRoute,
  appAnalyzeStockProfileRoute: appAnalyzeStockProfileRoute,
  appAnalyzePrortfolioIdIdeaGenerationRoute:
    appAnalyzePrortfolioIdIdeaGenerationRoute,
}

const appAnalyzeRouteRouteWithChildren = appAnalyzeRouteRoute._addFileChildren(
  appAnalyzeRouteRouteChildren,
)

interface appCreatePortfolioRouteRouteChildren {
  appCreatePortfolioMetadataRoute: typeof appCreatePortfolioMetadataRoute
  appCreatePortfolioPortfolioIdBenchmarkRoute: typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  appCreatePortfolioPortfolioIdCalculationsRoute: typeof appCreatePortfolioPortfolioIdCalculationsRoute
  appCreatePortfolioPortfolioIdCorrectionsRoute: typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  appCreatePortfolioPortfolioIdMultifundRoute: typeof appCreatePortfolioPortfolioIdMultifundRoute
  appCreatePortfolioPortfolioIdPreviewRoute: typeof appCreatePortfolioPortfolioIdPreviewRoute
  appCreatePortfolioPortfolioIdSubmitRoute: typeof appCreatePortfolioPortfolioIdSubmitRoute
  appCreatePortfolioPortfolioIdSummaryRoute: typeof appCreatePortfolioPortfolioIdSummaryRoute
  appCreatePortfolioPortfolioIdUniverseRoute: typeof appCreatePortfolioPortfolioIdUniverseRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
}

const appCreatePortfolioRouteRouteChildren: appCreatePortfolioRouteRouteChildren =
  {
    appCreatePortfolioMetadataRoute: appCreatePortfolioMetadataRoute,
    appCreatePortfolioPortfolioIdBenchmarkRoute:
      appCreatePortfolioPortfolioIdBenchmarkRoute,
    appCreatePortfolioPortfolioIdCalculationsRoute:
      appCreatePortfolioPortfolioIdCalculationsRoute,
    appCreatePortfolioPortfolioIdCorrectionsRoute:
      appCreatePortfolioPortfolioIdCorrectionsRoute,
    appCreatePortfolioPortfolioIdMultifundRoute:
      appCreatePortfolioPortfolioIdMultifundRoute,
    appCreatePortfolioPortfolioIdPreviewRoute:
      appCreatePortfolioPortfolioIdPreviewRoute,
    appCreatePortfolioPortfolioIdSubmitRoute:
      appCreatePortfolioPortfolioIdSubmitRoute,
    appCreatePortfolioPortfolioIdSummaryRoute:
      appCreatePortfolioPortfolioIdSummaryRoute,
    appCreatePortfolioPortfolioIdUniverseRoute:
      appCreatePortfolioPortfolioIdUniverseRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute,
  }

const appCreatePortfolioRouteRouteWithChildren =
  appCreatePortfolioRouteRoute._addFileChildren(
    appCreatePortfolioRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appAnalyzeRouteRoute: typeof appAnalyzeRouteRouteWithChildren
  appCreatePortfolioRouteRoute: typeof appCreatePortfolioRouteRouteWithChildren
  appDashboardRoute: typeof appDashboardRoute
  appReferenceDataRoute: typeof appReferenceDataRoute
  appSettingsRoute: typeof appSettingsRoute
  appHelpLazyRoute: typeof appHelpLazyRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAnalyzeRouteRoute: appAnalyzeRouteRouteWithChildren,
  appCreatePortfolioRouteRoute: appCreatePortfolioRouteRouteWithChildren,
  appDashboardRoute: appDashboardRoute,
  appReferenceDataRoute: appReferenceDataRoute,
  appSettingsRoute: appSettingsRoute,
  appHelpLazyRoute: appHelpLazyRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRegisterRoute: authRegisterRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
