/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appReferenceDataRouteImport } from './routes/(app)/reference-data'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appCreatePortfolioRouteRouteImport } from './routes/(app)/create-portfolio/route'
import { Route as appAnalyzeRouteRouteImport } from './routes/(app)/analyze/route'
import { Route as appCreatePortfolioMetadataRouteImport } from './routes/(app)/create-portfolio/metadata'
import { Route as appAnalyzeStockProfileRouteImport } from './routes/(app)/analyze/stock-profile'
import { Route as appAnalyzePortfolioIdIndexRouteImport } from './routes/(app)/analyze/$portfolioId/index'
import { Route as appCreatePortfolioPortfolioIdUniverseRouteImport } from './routes/(app)/create-portfolio/$portfolioId/universe'
import { Route as appCreatePortfolioPortfolioIdSubmitRouteImport } from './routes/(app)/create-portfolio/$portfolioId/submit'
import { Route as appCreatePortfolioPortfolioIdPreviewRouteImport } from './routes/(app)/create-portfolio/$portfolioId/preview'
import { Route as appCreatePortfolioPortfolioIdMultiFundRouteImport } from './routes/(app)/create-portfolio/$portfolioId/multi-fund'
import { Route as appCreatePortfolioPortfolioIdCorrectionsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/corrections'
import { Route as appCreatePortfolioPortfolioIdCalculationsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/calculations'
import { Route as appCreatePortfolioPortfolioIdBenchmarkRouteImport } from './routes/(app)/create-portfolio/$portfolioId/benchmark'
import { Route as appAnalyzePortfolioIdIdeaGenerationRouteRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/route'
import { Route as appAnalyzePortfolioIdIdeaGenerationIndexRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/index'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
import { Route as appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport } from './routes/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'
import { Route as appAnalyzePortfolioIdIdeaGenerationTopStocksRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/top-stocks'
import { Route as appAnalyzePortfolioIdIdeaGenerationScreeningRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/screening'
import { Route as appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/regimes/route'
import { Route as appAnalyzePortfolioIdIdeaGenerationRegimesIndexRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/regimes/index'
import { Route as appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
import { Route as appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRouteImport } from './routes/(app)/analyze/$portfolioId/idea-generation/regimes/economic-surprise'

const appHelpLazyRouteImport = createFileRoute('/(app)/help')()

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appHelpLazyRoute = appHelpLazyRouteImport
  .update({
    id: '/help',
    path: '/help',
    getParentRoute: () => appRouteRoute,
  } as any)
  .lazy(() => import('./routes/(app)/help.lazy').then((d) => d.Route))
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appReferenceDataRoute = appReferenceDataRouteImport.update({
  id: '/reference-data',
  path: '/reference-data',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreatePortfolioRouteRoute = appCreatePortfolioRouteRouteImport.update({
  id: '/create-portfolio',
  path: '/create-portfolio',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyzeRouteRoute = appAnalyzeRouteRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreatePortfolioMetadataRoute =
  appCreatePortfolioMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appAnalyzeStockProfileRoute = appAnalyzeStockProfileRouteImport.update({
  id: '/stock-profile',
  path: '/stock-profile',
  getParentRoute: () => appAnalyzeRouteRoute,
} as any)
const appAnalyzePortfolioIdIndexRoute =
  appAnalyzePortfolioIdIndexRouteImport.update({
    id: '/$portfolioId/',
    path: '/$portfolioId/',
    getParentRoute: () => appAnalyzeRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdUniverseRoute =
  appCreatePortfolioPortfolioIdUniverseRouteImport.update({
    id: '/$portfolioId/universe',
    path: '/$portfolioId/universe',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdSubmitRoute =
  appCreatePortfolioPortfolioIdSubmitRouteImport.update({
    id: '/$portfolioId/submit',
    path: '/$portfolioId/submit',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdPreviewRoute =
  appCreatePortfolioPortfolioIdPreviewRouteImport.update({
    id: '/$portfolioId/preview',
    path: '/$portfolioId/preview',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdMultiFundRoute =
  appCreatePortfolioPortfolioIdMultiFundRouteImport.update({
    id: '/$portfolioId/multi-fund',
    path: '/$portfolioId/multi-fund',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCorrectionsRoute =
  appCreatePortfolioPortfolioIdCorrectionsRouteImport.update({
    id: '/$portfolioId/corrections',
    path: '/$portfolioId/corrections',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCalculationsRoute =
  appCreatePortfolioPortfolioIdCalculationsRouteImport.update({
    id: '/$portfolioId/calculations',
    path: '/$portfolioId/calculations',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdBenchmarkRoute =
  appCreatePortfolioPortfolioIdBenchmarkRouteImport.update({
    id: '/$portfolioId/benchmark',
    path: '/$portfolioId/benchmark',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationRouteRoute =
  appAnalyzePortfolioIdIdeaGenerationRouteRouteImport.update({
    id: '/$portfolioId/idea-generation',
    path: '/$portfolioId/idea-generation',
    getParentRoute: () => appAnalyzeRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationIndexRoute =
  appAnalyzePortfolioIdIdeaGenerationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport.update({
    id: '/$portfolioId/create-benchmark/preview',
    path: '/$portfolioId/create-benchmark/preview',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport.update({
    id: '/$portfolioId/create-benchmark/metadata',
    path: '/$portfolioId/create-benchmark/metadata',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute =
  appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport.update({
    id: '/$portfolioId/create-benchmark/corrections',
    path: '/$portfolioId/create-benchmark/corrections',
    getParentRoute: () => appCreatePortfolioRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationTopStocksRoute =
  appAnalyzePortfolioIdIdeaGenerationTopStocksRouteImport.update({
    id: '/top-stocks',
    path: '/top-stocks',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationScreeningRoute =
  appAnalyzePortfolioIdIdeaGenerationScreeningRouteImport.update({
    id: '/screening',
    path: '/screening',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute =
  appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteImport.update({
    id: '/regimes',
    path: '/regimes',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute =
  appAnalyzePortfolioIdIdeaGenerationRegimesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute =
  appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRouteImport.update({
    id: '/leading-indicator',
    path: '/leading-indicator',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute,
  } as any)
const appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute =
  appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRouteImport.update({
    id: '/economic-surprise',
    path: '/economic-surprise',
    getParentRoute: () => appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authIndexRoute
  '/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/reference-data': typeof appReferenceDataRoute
  '/settings': typeof appSettingsRoute
  '/register': typeof authRegisterRoute
  '/help': typeof appHelpLazyRoute
  '/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/analyze/$portfolioId/idea-generation': typeof appAnalyzePortfolioIdIdeaGenerationRouteRouteWithChildren
  '/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/create-portfolio/$portfolioId/multi-fund': typeof appCreatePortfolioPortfolioIdMultiFundRoute
  '/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/analyze/$portfolioId': typeof appAnalyzePortfolioIdIndexRoute
  '/analyze/$portfolioId/idea-generation/regimes': typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteWithChildren
  '/analyze/$portfolioId/idea-generation/screening': typeof appAnalyzePortfolioIdIdeaGenerationScreeningRoute
  '/analyze/$portfolioId/idea-generation/top-stocks': typeof appAnalyzePortfolioIdIdeaGenerationTopStocksRoute
  '/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
  '/analyze/$portfolioId/idea-generation/': typeof appAnalyzePortfolioIdIdeaGenerationIndexRoute
  '/analyze/$portfolioId/idea-generation/regimes/economic-surprise': typeof appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute
  '/analyze/$portfolioId/idea-generation/regimes/leading-indicator': typeof appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute
  '/analyze/$portfolioId/idea-generation/regimes/': typeof appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authIndexRoute
  '/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/dashboard': typeof appDashboardRoute
  '/reference-data': typeof appReferenceDataRoute
  '/settings': typeof appSettingsRoute
  '/register': typeof authRegisterRoute
  '/help': typeof appHelpLazyRoute
  '/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/create-portfolio/$portfolioId/multi-fund': typeof appCreatePortfolioPortfolioIdMultiFundRoute
  '/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/analyze/$portfolioId': typeof appAnalyzePortfolioIdIndexRoute
  '/analyze/$portfolioId/idea-generation/screening': typeof appAnalyzePortfolioIdIdeaGenerationScreeningRoute
  '/analyze/$portfolioId/idea-generation/top-stocks': typeof appAnalyzePortfolioIdIdeaGenerationTopStocksRoute
  '/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
  '/analyze/$portfolioId/idea-generation': typeof appAnalyzePortfolioIdIdeaGenerationIndexRoute
  '/analyze/$portfolioId/idea-generation/regimes/economic-surprise': typeof appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute
  '/analyze/$portfolioId/idea-generation/regimes/leading-indicator': typeof appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute
  '/analyze/$portfolioId/idea-generation/regimes': typeof appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/analyze': typeof appAnalyzeRouteRouteWithChildren
  '/(app)/create-portfolio': typeof appCreatePortfolioRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/reference-data': typeof appReferenceDataRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/help': typeof appHelpLazyRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/analyze/stock-profile': typeof appAnalyzeStockProfileRoute
  '/(app)/create-portfolio/metadata': typeof appCreatePortfolioMetadataRoute
  '/(app)/analyze/$portfolioId/idea-generation': typeof appAnalyzePortfolioIdIdeaGenerationRouteRouteWithChildren
  '/(app)/create-portfolio/$portfolioId/benchmark': typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  '/(app)/create-portfolio/$portfolioId/calculations': typeof appCreatePortfolioPortfolioIdCalculationsRoute
  '/(app)/create-portfolio/$portfolioId/corrections': typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  '/(app)/create-portfolio/$portfolioId/multi-fund': typeof appCreatePortfolioPortfolioIdMultiFundRoute
  '/(app)/create-portfolio/$portfolioId/preview': typeof appCreatePortfolioPortfolioIdPreviewRoute
  '/(app)/create-portfolio/$portfolioId/submit': typeof appCreatePortfolioPortfolioIdSubmitRoute
  '/(app)/create-portfolio/$portfolioId/universe': typeof appCreatePortfolioPortfolioIdUniverseRoute
  '/(app)/analyze/$portfolioId/': typeof appAnalyzePortfolioIdIndexRoute
  '/(app)/analyze/$portfolioId/idea-generation/regimes': typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteWithChildren
  '/(app)/analyze/$portfolioId/idea-generation/screening': typeof appAnalyzePortfolioIdIdeaGenerationScreeningRoute
  '/(app)/analyze/$portfolioId/idea-generation/top-stocks': typeof appAnalyzePortfolioIdIdeaGenerationTopStocksRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections': typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata': typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  '/(app)/create-portfolio/$portfolioId/create-benchmark/preview': typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
  '/(app)/analyze/$portfolioId/idea-generation/': typeof appAnalyzePortfolioIdIdeaGenerationIndexRoute
  '/(app)/analyze/$portfolioId/idea-generation/regimes/economic-surprise': typeof appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute
  '/(app)/analyze/$portfolioId/idea-generation/regimes/leading-indicator': typeof appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute
  '/(app)/analyze/$portfolioId/idea-generation/regimes/': typeof appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/create-portfolio'
    | '/dashboard'
    | '/reference-data'
    | '/settings'
    | '/register'
    | '/help'
    | '/analyze/stock-profile'
    | '/create-portfolio/metadata'
    | '/analyze/$portfolioId/idea-generation'
    | '/create-portfolio/$portfolioId/benchmark'
    | '/create-portfolio/$portfolioId/calculations'
    | '/create-portfolio/$portfolioId/corrections'
    | '/create-portfolio/$portfolioId/multi-fund'
    | '/create-portfolio/$portfolioId/preview'
    | '/create-portfolio/$portfolioId/submit'
    | '/create-portfolio/$portfolioId/universe'
    | '/analyze/$portfolioId'
    | '/analyze/$portfolioId/idea-generation/regimes'
    | '/analyze/$portfolioId/idea-generation/screening'
    | '/analyze/$portfolioId/idea-generation/top-stocks'
    | '/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/create-portfolio/$portfolioId/create-benchmark/preview'
    | '/analyze/$portfolioId/idea-generation/'
    | '/analyze/$portfolioId/idea-generation/regimes/economic-surprise'
    | '/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
    | '/analyze/$portfolioId/idea-generation/regimes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/create-portfolio'
    | '/dashboard'
    | '/reference-data'
    | '/settings'
    | '/register'
    | '/help'
    | '/analyze/stock-profile'
    | '/create-portfolio/metadata'
    | '/create-portfolio/$portfolioId/benchmark'
    | '/create-portfolio/$portfolioId/calculations'
    | '/create-portfolio/$portfolioId/corrections'
    | '/create-portfolio/$portfolioId/multi-fund'
    | '/create-portfolio/$portfolioId/preview'
    | '/create-portfolio/$portfolioId/submit'
    | '/create-portfolio/$portfolioId/universe'
    | '/analyze/$portfolioId'
    | '/analyze/$portfolioId/idea-generation/screening'
    | '/analyze/$portfolioId/idea-generation/top-stocks'
    | '/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/create-portfolio/$portfolioId/create-benchmark/preview'
    | '/analyze/$portfolioId/idea-generation'
    | '/analyze/$portfolioId/idea-generation/regimes/economic-surprise'
    | '/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
    | '/analyze/$portfolioId/idea-generation/regimes'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/analyze'
    | '/(app)/create-portfolio'
    | '/(app)/dashboard'
    | '/(app)/reference-data'
    | '/(app)/settings'
    | '/(auth)/register'
    | '/(app)/help'
    | '/(auth)/'
    | '/(app)/analyze/stock-profile'
    | '/(app)/create-portfolio/metadata'
    | '/(app)/analyze/$portfolioId/idea-generation'
    | '/(app)/create-portfolio/$portfolioId/benchmark'
    | '/(app)/create-portfolio/$portfolioId/calculations'
    | '/(app)/create-portfolio/$portfolioId/corrections'
    | '/(app)/create-portfolio/$portfolioId/multi-fund'
    | '/(app)/create-portfolio/$portfolioId/preview'
    | '/(app)/create-portfolio/$portfolioId/submit'
    | '/(app)/create-portfolio/$portfolioId/universe'
    | '/(app)/analyze/$portfolioId/'
    | '/(app)/analyze/$portfolioId/idea-generation/regimes'
    | '/(app)/analyze/$portfolioId/idea-generation/screening'
    | '/(app)/analyze/$portfolioId/idea-generation/top-stocks'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
    | '/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
    | '/(app)/analyze/$portfolioId/idea-generation/'
    | '/(app)/analyze/$portfolioId/idea-generation/regimes/economic-surprise'
    | '/(app)/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
    | '/(app)/analyze/$portfolioId/idea-generation/regimes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRegisterRoute: typeof authRegisterRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/help': {
      id: '/(app)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof appHelpLazyRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reference-data': {
      id: '/(app)/reference-data'
      path: '/reference-data'
      fullPath: '/reference-data'
      preLoaderRoute: typeof appReferenceDataRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-portfolio': {
      id: '/(app)/create-portfolio'
      path: '/create-portfolio'
      fullPath: '/create-portfolio'
      preLoaderRoute: typeof appCreatePortfolioRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analyze': {
      id: '/(app)/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof appAnalyzeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-portfolio/metadata': {
      id: '/(app)/create-portfolio/metadata'
      path: '/metadata'
      fullPath: '/create-portfolio/metadata'
      preLoaderRoute: typeof appCreatePortfolioMetadataRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/analyze/stock-profile': {
      id: '/(app)/analyze/stock-profile'
      path: '/stock-profile'
      fullPath: '/analyze/stock-profile'
      preLoaderRoute: typeof appAnalyzeStockProfileRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/analyze/$portfolioId/': {
      id: '/(app)/analyze/$portfolioId/'
      path: '/$portfolioId'
      fullPath: '/analyze/$portfolioId'
      preLoaderRoute: typeof appAnalyzePortfolioIdIndexRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/universe': {
      id: '/(app)/create-portfolio/$portfolioId/universe'
      path: '/$portfolioId/universe'
      fullPath: '/create-portfolio/$portfolioId/universe'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdUniverseRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/submit': {
      id: '/(app)/create-portfolio/$portfolioId/submit'
      path: '/$portfolioId/submit'
      fullPath: '/create-portfolio/$portfolioId/submit'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdSubmitRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/preview': {
      id: '/(app)/create-portfolio/$portfolioId/preview'
      path: '/$portfolioId/preview'
      fullPath: '/create-portfolio/$portfolioId/preview'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdPreviewRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/multi-fund': {
      id: '/(app)/create-portfolio/$portfolioId/multi-fund'
      path: '/$portfolioId/multi-fund'
      fullPath: '/create-portfolio/$portfolioId/multi-fund'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdMultiFundRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/corrections': {
      id: '/(app)/create-portfolio/$portfolioId/corrections'
      path: '/$portfolioId/corrections'
      fullPath: '/create-portfolio/$portfolioId/corrections'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCorrectionsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/calculations': {
      id: '/(app)/create-portfolio/$portfolioId/calculations'
      path: '/$portfolioId/calculations'
      fullPath: '/create-portfolio/$portfolioId/calculations'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCalculationsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/benchmark': {
      id: '/(app)/create-portfolio/$portfolioId/benchmark'
      path: '/$portfolioId/benchmark'
      fullPath: '/create-portfolio/$portfolioId/benchmark'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdBenchmarkRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation': {
      id: '/(app)/analyze/$portfolioId/idea-generation'
      path: '/$portfolioId/idea-generation'
      fullPath: '/analyze/$portfolioId/idea-generation'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRouteImport
      parentRoute: typeof appAnalyzeRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/': {
      id: '/(app)/analyze/$portfolioId/idea-generation/'
      path: '/'
      fullPath: '/analyze/$portfolioId/idea-generation/'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationIndexRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/preview': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/preview'
      path: '/$portfolioId/create-benchmark/preview'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/preview'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/metadata'
      path: '/$portfolioId/create-benchmark/metadata'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/metadata'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections': {
      id: '/(app)/create-portfolio/$portfolioId/create-benchmark/corrections'
      path: '/$portfolioId/create-benchmark/corrections'
      fullPath: '/create-portfolio/$portfolioId/create-benchmark/corrections'
      preLoaderRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRouteImport
      parentRoute: typeof appCreatePortfolioRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/top-stocks': {
      id: '/(app)/analyze/$portfolioId/idea-generation/top-stocks'
      path: '/top-stocks'
      fullPath: '/analyze/$portfolioId/idea-generation/top-stocks'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationTopStocksRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/screening': {
      id: '/(app)/analyze/$portfolioId/idea-generation/screening'
      path: '/screening'
      fullPath: '/analyze/$portfolioId/idea-generation/screening'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationScreeningRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/regimes': {
      id: '/(app)/analyze/$portfolioId/idea-generation/regimes'
      path: '/regimes'
      fullPath: '/analyze/$portfolioId/idea-generation/regimes'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/regimes/': {
      id: '/(app)/analyze/$portfolioId/idea-generation/regimes/'
      path: '/'
      fullPath: '/analyze/$portfolioId/idea-generation/regimes/'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesIndexRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/regimes/leading-indicator': {
      id: '/(app)/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
      path: '/leading-indicator'
      fullPath: '/analyze/$portfolioId/idea-generation/regimes/leading-indicator'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute
    }
    '/(app)/analyze/$portfolioId/idea-generation/regimes/economic-surprise': {
      id: '/(app)/analyze/$portfolioId/idea-generation/regimes/economic-surprise'
      path: '/economic-surprise'
      fullPath: '/analyze/$portfolioId/idea-generation/regimes/economic-surprise'
      preLoaderRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRouteImport
      parentRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute
    }
  }
}

interface appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteChildren {
  appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute
  appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute
  appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute
}

const appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteChildren: appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteChildren =
  {
    appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute:
      appAnalyzePortfolioIdIdeaGenerationRegimesEconomicSurpriseRoute,
    appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute:
      appAnalyzePortfolioIdIdeaGenerationRegimesLeadingIndicatorRoute,
    appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute:
      appAnalyzePortfolioIdIdeaGenerationRegimesIndexRoute,
  }

const appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteWithChildren =
  appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute._addFileChildren(
    appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteChildren,
  )

interface appAnalyzePortfolioIdIdeaGenerationRouteRouteChildren {
  appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute: typeof appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteWithChildren
  appAnalyzePortfolioIdIdeaGenerationScreeningRoute: typeof appAnalyzePortfolioIdIdeaGenerationScreeningRoute
  appAnalyzePortfolioIdIdeaGenerationTopStocksRoute: typeof appAnalyzePortfolioIdIdeaGenerationTopStocksRoute
  appAnalyzePortfolioIdIdeaGenerationIndexRoute: typeof appAnalyzePortfolioIdIdeaGenerationIndexRoute
}

const appAnalyzePortfolioIdIdeaGenerationRouteRouteChildren: appAnalyzePortfolioIdIdeaGenerationRouteRouteChildren =
  {
    appAnalyzePortfolioIdIdeaGenerationRegimesRouteRoute:
      appAnalyzePortfolioIdIdeaGenerationRegimesRouteRouteWithChildren,
    appAnalyzePortfolioIdIdeaGenerationScreeningRoute:
      appAnalyzePortfolioIdIdeaGenerationScreeningRoute,
    appAnalyzePortfolioIdIdeaGenerationTopStocksRoute:
      appAnalyzePortfolioIdIdeaGenerationTopStocksRoute,
    appAnalyzePortfolioIdIdeaGenerationIndexRoute:
      appAnalyzePortfolioIdIdeaGenerationIndexRoute,
  }

const appAnalyzePortfolioIdIdeaGenerationRouteRouteWithChildren =
  appAnalyzePortfolioIdIdeaGenerationRouteRoute._addFileChildren(
    appAnalyzePortfolioIdIdeaGenerationRouteRouteChildren,
  )

interface appAnalyzeRouteRouteChildren {
  appAnalyzeStockProfileRoute: typeof appAnalyzeStockProfileRoute
  appAnalyzePortfolioIdIdeaGenerationRouteRoute: typeof appAnalyzePortfolioIdIdeaGenerationRouteRouteWithChildren
  appAnalyzePortfolioIdIndexRoute: typeof appAnalyzePortfolioIdIndexRoute
}

const appAnalyzeRouteRouteChildren: appAnalyzeRouteRouteChildren = {
  appAnalyzeStockProfileRoute: appAnalyzeStockProfileRoute,
  appAnalyzePortfolioIdIdeaGenerationRouteRoute:
    appAnalyzePortfolioIdIdeaGenerationRouteRouteWithChildren,
  appAnalyzePortfolioIdIndexRoute: appAnalyzePortfolioIdIndexRoute,
}

const appAnalyzeRouteRouteWithChildren = appAnalyzeRouteRoute._addFileChildren(
  appAnalyzeRouteRouteChildren,
)

interface appCreatePortfolioRouteRouteChildren {
  appCreatePortfolioMetadataRoute: typeof appCreatePortfolioMetadataRoute
  appCreatePortfolioPortfolioIdBenchmarkRoute: typeof appCreatePortfolioPortfolioIdBenchmarkRoute
  appCreatePortfolioPortfolioIdCalculationsRoute: typeof appCreatePortfolioPortfolioIdCalculationsRoute
  appCreatePortfolioPortfolioIdCorrectionsRoute: typeof appCreatePortfolioPortfolioIdCorrectionsRoute
  appCreatePortfolioPortfolioIdMultiFundRoute: typeof appCreatePortfolioPortfolioIdMultiFundRoute
  appCreatePortfolioPortfolioIdPreviewRoute: typeof appCreatePortfolioPortfolioIdPreviewRoute
  appCreatePortfolioPortfolioIdSubmitRoute: typeof appCreatePortfolioPortfolioIdSubmitRoute
  appCreatePortfolioPortfolioIdUniverseRoute: typeof appCreatePortfolioPortfolioIdUniverseRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute
  appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute: typeof appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute
}

const appCreatePortfolioRouteRouteChildren: appCreatePortfolioRouteRouteChildren =
  {
    appCreatePortfolioMetadataRoute: appCreatePortfolioMetadataRoute,
    appCreatePortfolioPortfolioIdBenchmarkRoute:
      appCreatePortfolioPortfolioIdBenchmarkRoute,
    appCreatePortfolioPortfolioIdCalculationsRoute:
      appCreatePortfolioPortfolioIdCalculationsRoute,
    appCreatePortfolioPortfolioIdCorrectionsRoute:
      appCreatePortfolioPortfolioIdCorrectionsRoute,
    appCreatePortfolioPortfolioIdMultiFundRoute:
      appCreatePortfolioPortfolioIdMultiFundRoute,
    appCreatePortfolioPortfolioIdPreviewRoute:
      appCreatePortfolioPortfolioIdPreviewRoute,
    appCreatePortfolioPortfolioIdSubmitRoute:
      appCreatePortfolioPortfolioIdSubmitRoute,
    appCreatePortfolioPortfolioIdUniverseRoute:
      appCreatePortfolioPortfolioIdUniverseRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkCorrectionsRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkMetadataRoute,
    appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute:
      appCreatePortfolioPortfolioIdCreateBenchmarkPreviewRoute,
  }

const appCreatePortfolioRouteRouteWithChildren =
  appCreatePortfolioRouteRoute._addFileChildren(
    appCreatePortfolioRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appAnalyzeRouteRoute: typeof appAnalyzeRouteRouteWithChildren
  appCreatePortfolioRouteRoute: typeof appCreatePortfolioRouteRouteWithChildren
  appDashboardRoute: typeof appDashboardRoute
  appReferenceDataRoute: typeof appReferenceDataRoute
  appSettingsRoute: typeof appSettingsRoute
  appHelpLazyRoute: typeof appHelpLazyRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAnalyzeRouteRoute: appAnalyzeRouteRouteWithChildren,
  appCreatePortfolioRouteRoute: appCreatePortfolioRouteRouteWithChildren,
  appDashboardRoute: appDashboardRoute,
  appReferenceDataRoute: appReferenceDataRoute,
  appSettingsRoute: appSettingsRoute,
  appHelpLazyRoute: appHelpLazyRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRegisterRoute: authRegisterRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
